/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ShopIndexLazyImport = createFileRoute('/shop/')()
const UserAccountIndexLazyImport = createFileRoute('/user/account/')()
const AboutAboutUsIndexLazyImport = createFileRoute('/about/aboutUs/')()
const AboutAboutProductIndexLazyImport = createFileRoute(
  '/about/aboutProduct/',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ShopIndexLazyRoute = ShopIndexLazyImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/shop/index.lazy').then((d) => d.Route))

const UserAccountIndexLazyRoute = UserAccountIndexLazyImport.update({
  id: '/user/account/',
  path: '/user/account/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/user/account/index.lazy').then((d) => d.Route),
)

const AboutAboutUsIndexLazyRoute = AboutAboutUsIndexLazyImport.update({
  id: '/about/aboutUs/',
  path: '/about/aboutUs/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/about/aboutUs/index.lazy').then((d) => d.Route),
)

const AboutAboutProductIndexLazyRoute = AboutAboutProductIndexLazyImport.update(
  {
    id: '/about/aboutProduct/',
    path: '/about/aboutProduct/',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/about/aboutProduct/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about/aboutProduct/': {
      id: '/about/aboutProduct/'
      path: '/about/aboutProduct'
      fullPath: '/about/aboutProduct'
      preLoaderRoute: typeof AboutAboutProductIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about/aboutUs/': {
      id: '/about/aboutUs/'
      path: '/about/aboutUs'
      fullPath: '/about/aboutUs'
      preLoaderRoute: typeof AboutAboutUsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/user/account/': {
      id: '/user/account/'
      path: '/user/account'
      fullPath: '/user/account'
      preLoaderRoute: typeof UserAccountIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/shop': typeof ShopIndexLazyRoute
  '/about/aboutProduct': typeof AboutAboutProductIndexLazyRoute
  '/about/aboutUs': typeof AboutAboutUsIndexLazyRoute
  '/user/account': typeof UserAccountIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/shop': typeof ShopIndexLazyRoute
  '/about/aboutProduct': typeof AboutAboutProductIndexLazyRoute
  '/about/aboutUs': typeof AboutAboutUsIndexLazyRoute
  '/user/account': typeof UserAccountIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/shop/': typeof ShopIndexLazyRoute
  '/about/aboutProduct/': typeof AboutAboutProductIndexLazyRoute
  '/about/aboutUs/': typeof AboutAboutUsIndexLazyRoute
  '/user/account/': typeof UserAccountIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shop'
    | '/about/aboutProduct'
    | '/about/aboutUs'
    | '/user/account'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shop' | '/about/aboutProduct' | '/about/aboutUs' | '/user/account'
  id:
    | '__root__'
    | '/'
    | '/shop/'
    | '/about/aboutProduct/'
    | '/about/aboutUs/'
    | '/user/account/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ShopIndexLazyRoute: typeof ShopIndexLazyRoute
  AboutAboutProductIndexLazyRoute: typeof AboutAboutProductIndexLazyRoute
  AboutAboutUsIndexLazyRoute: typeof AboutAboutUsIndexLazyRoute
  UserAccountIndexLazyRoute: typeof UserAccountIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ShopIndexLazyRoute: ShopIndexLazyRoute,
  AboutAboutProductIndexLazyRoute: AboutAboutProductIndexLazyRoute,
  AboutAboutUsIndexLazyRoute: AboutAboutUsIndexLazyRoute,
  UserAccountIndexLazyRoute: UserAccountIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/shop/",
        "/about/aboutProduct/",
        "/about/aboutUs/",
        "/user/account/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/shop/": {
      "filePath": "shop/index.lazy.tsx"
    },
    "/about/aboutProduct/": {
      "filePath": "about/aboutProduct/index.lazy.tsx"
    },
    "/about/aboutUs/": {
      "filePath": "about/aboutUs/index.lazy.tsx"
    },
    "/user/account/": {
      "filePath": "user/account/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
